<section class="content-header">
  <h1>Single Chord</h1>
  <ol class="breadcrumb">
    <li><a href="<?php echo $this->url->getBaseUri() ?>"><i class="fa fa-home"></i> Home</a></li>
    <li><a href="<?php echo $this->url->getBaseUri() ?>admin">Admin</a></li>
    <li class="active">Chord</li>
  </ol>
</section>
<section class="content">
  <div class="row">
    <div class="col-md-4 col-sm-12">
      <div class="box box-primary">
        <div class="box-header"><h3 class="box-title">Info Lagu</h3></div>
        <form role="form">
          <div class="box-body">
            <div class="form-group">
              <label for="inputArtist">Penyanyi</label>
              <input type="text" class="form-control" id="inputArtist" name="artist" placeholder="">
            </div>
            <div class="form-group">
              <label for="inputSongTitle">Judul lagu</label>
              <input type="text" class="form-control" id="inputSongTitle" name="song_title" placeholder="">
            </div>
            <div class="form-group">
              <label for="textInfo">Keterangan</label>
              <textarea class="form-control" rows="3" id="textInfo" name="info" placeholder=""></textarea>
            </div>
            <div class="input-group">
              <span class="input-group-addon"><strong>Kunci Dasar</strong></span>
              <select class="form-control" id="selectBaseChord" name="base_chord" placeholder="Nada Dasar">
                <option>C</option>
                <option>C&#9839;</option>
                <option>D</option>
                <option>D&#9839;</option>
                <option>E</option>
                <option>F</option>
                <option>F&#9839;</option>
                <option>G</option>
                <option>G&#9839;/A&#9837;</option>
                <option>A</option>
                <option>A&#9839;/B&#9837;</option>
                <option>B</option>
              </select>
            </div>
          </div>
          <div class="box-footer">
            <button type="submit" class="btn btn-primary">Simpan</button>
          </div>
        </form>
      </div>
    </div>
    <div class="col-md-8 col-sm-12">
      <div class="nav-tabs-custom">
        <ul class="nav nav-tabs tabs-lyric">
            <li class="active"><a href="#lyricText" data-toggle="tab">Text Lirik</a></li>
            <li><a href="#lyricChord" data-toggle="tab">Kord</a></li>
            <li class="pull-right"><a id="autoConvert" href="javascript:void(0)"><i class="fa fa-exchange"></i> Auto Convert</a></li>
        </ul>
        <div id="tabsLyricContent" class="tab-content">
            <div class="tab-pane fade active in" id="lyricText">
              <textarea type="text" class="form-control auto-expand" id="textLyric" placeholder="Ketik/paste lirik di sini..." rows="20" data-min-rows="3"></textarea>
            </div>
            <div class="tab-pane fade" id="lyricChord" style="overflow: auto;">
            </div>
        </div>
      </div>
    </div>
  </div>