<html>

<head>
  <meta charset="UTF-8">
  <title>NKord | Dashboard</title>
  <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
  <?php echo $this->tag->stylesheetLink('css/main.min.css') ?>
  <?php echo $this->tag->stylesheetLink('css/theme.min.css') ?>
  <?php echo $this->tag->stylesheetLink('css/nkord.css') ?>
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body class="skin-green sidebar-mini">
  <div class="wrapper">
    <?php echo $this->getContent(); ?>
  </div>

  <?php echo $this->tag->javascriptInclude("js/main.min.js"); ?>
  <?php echo $this->tag->javascriptInclude("js/nkord.js"); ?>

</body>

</html>
